### ISSUE TITLE
V3 support for event creation

### ISSUE THREAD

**Issue by grega** [chrisradfordltd/chiketto#6]
I notice that V1 endpoints are still being used for actions such as event creation / updating, is there a plan to update these to V3 soon?

**Comment by chrisradford** [comment]
There is indeed — the API deprecation is April 30th and the plan is to make the switch in early march as well as bumping the version to 1.0.

The actual API exposed by the gem shouldn't change at all.

**Comment by grega** [comment]
Good stuff, thanks! If there's anything I can do to help please let me know; can spare a few hours here & there.

**Comment by chrisradford** [comment]
If you fancied taking a run at it I'd be happy to look it over / update any of the tests. I think it's a fairly simple change, just changing the `legacy_endpoint` setting to `endpoint` and changing any parameters that have changed on the API (I haven't looked at the new V3 methods vs the V1's they replaced).

**Comment by grega** [comment]
I'll see if I can give it a shot in the next week or so!
